# Yarn Berry Configuration
# © Web8 UltraThinking – Ledjan Ahmati

enableGlobalCache: true
enableTelemetry: false
nodeLinker: node-modules

# Performance optimizations
enableHardenedMode: false
enableNetwork: true
pnpMode: loose

# Development
enableTimers: true
enableColors: true
