# EuroWeb Platform - Swiss Precision Configuration
# Yarn Berry 4.x with npm compatibility + Real API data integration
# © Web8 UltraThinking – Ledjan Ahmati

enableGlobalCache: true
enableTelemetry: false
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.1.0.cjs

# Swiss clockwork performance optimizations
enableHardenedMode: false
enableNetwork: true
enableMirror: true
compressionLevel: 9
pnpMode: loose

# Network optimization (Swiss precision)
httpRetry: 3
httpTimeout: 60000
networkTimeout: 600000

# Development experience
enableTimers: true
enableColors: true
progressBarStyle: patrick
preferInteractive: true

# Security & integrity
enableScripts: true
enableStrictSsl: true

# Package manager integration
packageManager: "yarn@4.1.0"

# Node.js optimization
nodeOptions: "--max-old-space-size=8192"

# Swiss precision logging
logLevel: info
