// components/AviationPDFTools.tsx
// Aviation PDF Export Tools - Professional Report Generation
// Weather Reports, Flight Plans, Calculations Export

'use client'

import { motion } from 'framer-motion'
import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'
import { Calculator, Download, FileText, Plane, Printer, Settings } from 'lucide-react'
import { useRef, useState } from 'react'

interface PDFTemplate {
    id: string
    name: string
    description: string
    type: 'weather' | 'flight_plan' | 'calculations' | 'custom'
    icon: any
}

interface WeatherReport {
    airports: string[]
    timestamp: string
    weatherData: any[]
    includeCharts: boolean
    includeForecast: boolean
}

interface FlightPlan {
    departure: string
    arrival: string
    route: string
    aircraft: string
    fuelPlanning: any
    weatherBriefing: any
}

const pdfTemplates: PDFTemplate[] = [
    {
        id: 'weather_brief',
        name: 'Weather Briefing',
        description: 'Complete weather report with METAR, TAF, and charts',
        type: 'weather',
        icon: FileText
    },
    {
        id: 'flight_plan',
        name: 'Flight Plan',
        description: 'Professional flight plan with navigation and fuel calculations',
        type: 'flight_plan',
        icon: Plane
    },
    {
        id: 'calculations_report',
        name: 'Calculations Report',
        description: 'Aviation calculations with formulas and results',
        type: 'calculations',
        icon: Calculator
    },
    {
        id: 'custom_report',
        name: 'Custom Report',
        description: 'Build your own report with selected components',
        type: 'custom',
        icon: Settings
    }
]

export default function AviationPDFTools() {
    const [selectedTemplate, setSelectedTemplate] = useState<PDFTemplate | null>(null)
    const [reportData, setReportData] = useState<any>({})
    const [isGenerating, setIsGenerating] = useState(false)
    const [includeHeader, setIncludeHeader] = useState(true)
    const [includeFooter, setIncludeFooter] = useState(true)
    const [includeCharts, setIncludeCharts] = useState(true)
    const reportRef = useRef<HTMLDivElement>(null)

    const generateWeatherBriefingPDF = async () => {
        const pdf = new jsPDF('p', 'mm', 'a4')
        const pageWidth = pdf.internal.pageSize.getWidth()
        const pageHeight = pdf.internal.pageSize.getHeight()

        // Header
        if (includeHeader) {
            pdf.setFillColor(30, 41, 59) // slate-800
            pdf.rect(0, 0, pageWidth, 40, 'F')

            pdf.setTextColor(255, 255, 255)
            pdf.setFontSize(20)
            pdf.setFont('helvetica', 'bold')
            pdf.text('Aviation Weather Briefing', 20, 20)

            pdf.setFontSize(12)
            pdf.setFont('helvetica', 'normal')
            pdf.text(`Generated: ${new Date().toLocaleString()}`, 20, 30)
            pdf.text('EuroWeb Ultra Aviation Platform', pageWidth - 80, 30)
        }

        // Content
        let yPosition = includeHeader ? 50 : 20

        // Airport Weather Data
        pdf.setTextColor(0, 0, 0)
        pdf.setFontSize(16)
        pdf.setFont('helvetica', 'bold')
        pdf.text('Weather Conditions', 20, yPosition)
        yPosition += 10

        // Sample airports
        const airports = ['LATI', 'EDDF', 'LOWW']
        airports.forEach((icao, index) => {
            pdf.setFontSize(14)
            pdf.setFont('helvetica', 'bold')
            pdf.text(`${icao} - Airport Weather`, 20, yPosition)
            yPosition += 8

            pdf.setFontSize(10)
            pdf.setFont('helvetica', 'normal')
            pdf.text('METAR: Clear skies, Wind 090/15KT, Visibility 10km+', 25, yPosition)
            yPosition += 5
            pdf.text('TAF: No significant weather expected for next 24 hours', 25, yPosition)
            yPosition += 5
            pdf.text('Temperature: 18°C, Pressure: 1013 hPa', 25, yPosition)
            yPosition += 10

            if (yPosition > pageHeight - 40) {
                pdf.addPage()
                yPosition = 20
            }
        })

        // Footer
        if (includeFooter) {
            const footerY = pageHeight - 20
            pdf.setFillColor(30, 41, 59)
            pdf.rect(0, footerY - 10, pageWidth, 20, 'F')

            pdf.setTextColor(255, 255, 255)
            pdf.setFontSize(8)
            pdf.text('Generated by EuroWeb Ultra Aviation Platform', 20, footerY - 5)
            pdf.text(`Page 1 of 1`, pageWidth - 30, footerY - 5)
        }

        return pdf
    }

    const generateFlightPlanPDF = async () => {
        const pdf = new jsPDF('p', 'mm', 'a4')
        const pageWidth = pdf.internal.pageSize.getWidth()

        // Header
        pdf.setFillColor(30, 41, 59)
        pdf.rect(0, 0, pageWidth, 40, 'F')

        pdf.setTextColor(255, 255, 255)
        pdf.setFontSize(20)
        pdf.setFont('helvetica', 'bold')
        pdf.text('Flight Plan', 20, 20)

        pdf.setFontSize(12)
        pdf.text(`Flight: LATI → EDDF`, 20, 30)
        pdf.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 60, 30)

        // Flight Details
        let yPos = 60
        pdf.setTextColor(0, 0, 0)
        pdf.setFontSize(14)
        pdf.setFont('helvetica', 'bold')
        pdf.text('Flight Details', 20, yPos)
        yPos += 15

        const flightData = [
            ['Departure:', 'LATI - Tirana International'],
            ['Arrival:', 'EDDF - Frankfurt Airport'],
            ['Aircraft:', 'Boeing 737-800'],
            ['Route:', 'LATI DCT VIE DCT EDDF'],
            ['Distance:', '685 NM'],
            ['Flight Time:', '1h 45min'],
            ['Fuel Required:', '2,450 L'],
            ['Alternate:', 'LOWW - Vienna International']
        ]

        pdf.setFontSize(10)
        pdf.setFont('helvetica', 'normal')
        flightData.forEach(([label, value]) => {
            pdf.setFont('helvetica', 'bold')
            pdf.text(label, 25, yPos)
            pdf.setFont('helvetica', 'normal')
            pdf.text(value, 80, yPos)
            yPos += 8
        })

        return pdf
    }

    const generateCalculationsPDF = async () => {
        const pdf = new jsPDF('p', 'mm', 'a4')
        const pageWidth = pdf.internal.pageSize.getWidth()

        // Header
        pdf.setFillColor(30, 41, 59)
        pdf.rect(0, 0, pageWidth, 40, 'F')

        pdf.setTextColor(255, 255, 255)
        pdf.setFontSize(20)
        pdf.setFont('helvetica', 'bold')
        pdf.text('Aviation Calculations Report', 20, 20)

        // Sample calculations
        let yPos = 60
        pdf.setTextColor(0, 0, 0)
        pdf.setFontSize(14)
        pdf.setFont('helvetica', 'bold')
        pdf.text('Fuel Calculations', 20, yPos)
        yPos += 15

        const calculations = [
            { name: 'Trip Fuel', result: '1,850 L', formula: 'Distance × Fuel Factor' },
            { name: 'Reserve Fuel', result: '450 L', formula: '45min at cruise consumption' },
            { name: 'Taxi Fuel', result: '150 L', formula: 'Standard taxi allowance' },
            { name: 'Total Fuel', result: '2,450 L', formula: 'Trip + Reserve + Taxi' }
        ]

        pdf.setFontSize(10)
        calculations.forEach(calc => {
            pdf.setFont('helvetica', 'bold')
            pdf.text(`${calc.name}:`, 25, yPos)
            pdf.setFont('helvetica', 'normal')
            pdf.text(calc.result, 80, yPos)
            pdf.setFontSize(8)
            pdf.text(`Formula: ${calc.formula}`, 25, yPos + 4)
            pdf.setFontSize(10)
            yPos += 12
        })

        return pdf
    }

    const generatePDF = async () => {
        if (!selectedTemplate) return

        setIsGenerating(true)

        try {
            let pdf: jsPDF

            switch (selectedTemplate.type) {
                case 'weather':
                    pdf = await generateWeatherBriefingPDF()
                    break
                case 'flight_plan':
                    pdf = await generateFlightPlanPDF()
                    break
                case 'calculations':
                    pdf = await generateCalculationsPDF()
                    break
                default:
                    pdf = await generateWeatherBriefingPDF()
            }

            // Download the PDF
            pdf.save(`${selectedTemplate.name.toLowerCase().replace(/\s+/g, '_')}_${Date.now()}.pdf`)
        } catch (error) {
            console.error('PDF generation error:', error)
        } finally {
            setIsGenerating(false)
        }
    }

    const generateScreenshotPDF = async () => {
        if (!reportRef.current) return

        setIsGenerating(true)

        try {
            const canvas = await html2canvas(reportRef.current)
            const imgData = canvas.toDataURL('image/png')

            const pdf = new jsPDF('p', 'mm', 'a4')
            const pdfWidth = pdf.internal.pageSize.getWidth()
            const pdfHeight = pdf.internal.pageSize.getHeight()
            const imgWidth = canvas.width
            const imgHeight = canvas.height
            const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight)
            const imgX = (pdfWidth - imgWidth * ratio) / 2
            const imgY = 0

            pdf.addImage(imgData, 'PNG', imgX, imgY, imgWidth * ratio, imgHeight * ratio)
            pdf.save(`aviation_screenshot_${Date.now()}.pdf`)
        } catch (error) {
            console.error('Screenshot PDF error:', error)
        } finally {
            setIsGenerating(false)
        }
    }

    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-800 text-white p-6">
            {/* Header */}
            <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                className="mb-8"
            >
                <div className="flex items-center justify-between mb-6">
                    <div className="flex items-center gap-3">
                        <div className="w-12 h-12 bg-gradient-to-r from-purple-500 to-pink-500 rounded-xl flex items-center justify-center">
                            <FileText className="w-6 h-6 text-white" />
                        </div>
                        <div>
                            <h1 className="text-3xl font-bold bg-gradient-to-r from-white to-purple-200 bg-clip-text text-transparent">
                                Aviation PDF Tools
                            </h1>
                            <p className="text-purple-200">Professional report generation and export</p>
                        </div>
                    </div>
                </div>
            </motion.div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Template Selection */}
                <motion.div
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    className="lg:col-span-1"
                >
                    <div className="bg-slate-800/50 backdrop-blur-xl rounded-2xl border border-slate-700 p-6">
                        <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                            <FileText className="w-5 h-5 text-purple-400" />
                            PDF Templates
                        </h2>

                        <div className="space-y-3">
                            {pdfTemplates.map((template) => {
                                const Icon = template.icon
                                return (
                                    <button
                                        key={template.id}
                                        onClick={() => setSelectedTemplate(template)}
                                        className={`w-full p-4 rounded-lg border transition-all text-left ${selectedTemplate?.id === template.id
                                                ? 'bg-purple-600/20 border-purple-400'
                                                : 'bg-slate-700/30 border-slate-600 hover:border-slate-500'
                                            }`}
                                    >
                                        <div className="flex items-center gap-3 mb-2">
                                            <Icon className="w-5 h-5 text-purple-400" />
                                            <span className="font-bold">{template.name}</span>
                                        </div>
                                        <p className="text-sm text-slate-400">{template.description}</p>
                                    </button>
                                )
                            })}
                        </div>
                    </div>
                </motion.div>

                {/* Configuration & Preview */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="lg:col-span-2"
                >
                    <div className="bg-slate-800/50 backdrop-blur-xl rounded-2xl border border-slate-700 p-6">
                        <h2 className="text-xl font-bold mb-4">
                            {selectedTemplate ? `Configure ${selectedTemplate.name}` : 'Select a Template'}
                        </h2>

                        {selectedTemplate ? (
                            <div className="space-y-6">
                                {/* Options */}
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                    <label className="flex items-center gap-2">
                                        <input
                                            type="checkbox"
                                            checked={includeHeader}
                                            onChange={(e) => setIncludeHeader(e.target.checked)}
                                            className="rounded bg-slate-700 border-slate-600"
                                        />
                                        <span className="text-sm">Include Header</span>
                                    </label>
                                    <label className="flex items-center gap-2">
                                        <input
                                            type="checkbox"
                                            checked={includeFooter}
                                            onChange={(e) => setIncludeFooter(e.target.checked)}
                                            className="rounded bg-slate-700 border-slate-600"
                                        />
                                        <span className="text-sm">Include Footer</span>
                                    </label>
                                    <label className="flex items-center gap-2">
                                        <input
                                            type="checkbox"
                                            checked={includeCharts}
                                            onChange={(e) => setIncludeCharts(e.target.checked)}
                                            className="rounded bg-slate-700 border-slate-600"
                                        />
                                        <span className="text-sm">Include Charts</span>
                                    </label>
                                </div>

                                {/* Preview */}
                                <div ref={reportRef} className="bg-white text-black p-6 rounded-lg min-h-96">
                                    <div className="text-center border-b border-gray-300 pb-4 mb-6">
                                        <h1 className="text-2xl font-bold text-gray-800">{selectedTemplate.name}</h1>
                                        <p className="text-gray-600">Generated on {new Date().toLocaleDateString()}</p>
                                    </div>

                                    {selectedTemplate.type === 'weather' && (
                                        <div>
                                            <h2 className="text-lg font-bold mb-4">Weather Briefing</h2>
                                            <div className="space-y-4">
                                                <div className="border border-gray-300 p-4 rounded">
                                                    <h3 className="font-bold">LATI - Tirana International</h3>
                                                    <p className="text-sm">METAR: Clear skies, Wind 090/15KT</p>
                                                    <p className="text-sm">Temperature: 18°C, Pressure: 1013 hPa</p>
                                                </div>
                                                <div className="border border-gray-300 p-4 rounded">
                                                    <h3 className="font-bold">EDDF - Frankfurt Airport</h3>
                                                    <p className="text-sm">METAR: Partly cloudy, Wind 270/10KT</p>
                                                    <p className="text-sm">Temperature: 15°C, Pressure: 1015 hPa</p>
                                                </div>
                                            </div>
                                        </div>
                                    )}

                                    {selectedTemplate.type === 'flight_plan' && (
                                        <div>
                                            <h2 className="text-lg font-bold mb-4">Flight Plan Details</h2>
                                            <div className="grid grid-cols-2 gap-4">
                                                <div>
                                                    <p><strong>Departure:</strong> LATI</p>
                                                    <p><strong>Arrival:</strong> EDDF</p>
                                                    <p><strong>Aircraft:</strong> Boeing 737-800</p>
                                                </div>
                                                <div>
                                                    <p><strong>Distance:</strong> 685 NM</p>
                                                    <p><strong>Flight Time:</strong> 1h 45min</p>
                                                    <p><strong>Fuel:</strong> 2,450 L</p>
                                                </div>
                                            </div>
                                        </div>
                                    )}

                                    {selectedTemplate.type === 'calculations' && (
                                        <div>
                                            <h2 className="text-lg font-bold mb-4">Aviation Calculations</h2>
                                            <div className="space-y-3">
                                                <div className="border border-gray-300 p-3 rounded">
                                                    <p><strong>Fuel Consumption:</strong> 1,850 L</p>
                                                    <p className="text-sm text-gray-600">Formula: Distance × Fuel Factor</p>
                                                </div>
                                                <div className="border border-gray-300 p-3 rounded">
                                                    <p><strong>Ground Speed:</strong> 425 kts</p>
                                                    <p className="text-sm text-gray-600">Formula: TAS + Wind Component</p>
                                                </div>
                                            </div>
                                        </div>
                                    )}
                                </div>

                                {/* Action Buttons */}
                                <div className="flex gap-4">
                                    <button
                                        onClick={generatePDF}
                                        disabled={isGenerating}
                                        className="flex-1 py-3 bg-purple-600 hover:bg-purple-700 disabled:opacity-50 rounded-lg font-medium transition-colors flex items-center justify-center gap-2"
                                    >
                                        {isGenerating ? (
                                            <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                                        ) : (
                                            <Download className="w-4 h-4" />
                                        )}
                                        Generate PDF
                                    </button>
                                    <button
                                        onClick={generateScreenshotPDF}
                                        disabled={isGenerating}
                                        className="px-6 py-3 bg-slate-600 hover:bg-slate-700 disabled:opacity-50 rounded-lg font-medium transition-colors flex items-center gap-2"
                                    >
                                        <Printer className="w-4 h-4" />
                                        Screenshot
                                    </button>
                                </div>
                            </div>
                        ) : (
                            <div className="text-center py-12">
                                <FileText className="w-16 h-16 text-slate-500 mx-auto mb-4" />
                                <h3 className="text-lg font-bold text-slate-400 mb-2">Select a PDF Template</h3>
                                <p className="text-slate-500">Choose from weather briefings, flight plans, or custom reports</p>
                            </div>
                        )}
                    </div>
                </motion.div>
            </div>
        </div>
    )
}
