declare const styles: {
    readonly 'agi-control': string
    readonly 'neural-tools-root': string
    readonly 'neural-tools-header': string
    readonly 'neural-tools-title': string
    readonly 'neural-tools-subtitle': string
    readonly 'neural-tools-grid': string
    readonly 'neural-tools-card': string
    readonly 'neural-tools-card-title': string
    readonly 'neural-tools-card-desc': string
    readonly 'neural-tools-btn': string
    readonly 'dashboard-root': string
    readonly 'dashboard-header': string
    readonly 'dashboard-header-content': string
    readonly 'dashboard-title': string
    readonly 'dashboard-subtitle': string
    readonly 'dashboard-info': string
    readonly 'dashboard-status': string
    readonly 'dashboard-status-title': string
    readonly 'dashboard-status-subtitle': string
    readonly 'dashboard-metrics': string
    readonly 'dashboard-metric': string
    readonly 'dashboard-metric-label': string
    readonly 'dashboard-metric-value': string
    readonly 'dashboard-metric-sublabel': string
    readonly 'dashboard-additional-metrics': string
    readonly 'dashboard-small-metric': string
    readonly 'dashboard-small-metric-label': string
    readonly 'dashboard-small-metric-value': string
    readonly 'dashboard-small-metric-sublabel': string
    readonly 'dashboard-control-center': string
    readonly 'dashboard-control-title': string
    readonly 'dashboard-action-buttons': string
    readonly 'dashboard-btn': string
    readonly 'dashboard-system-controls': string
    readonly 'dashboard-controls-title': string
    readonly 'dashboard-controls-buttons': string
    readonly 'dashboard-control-btn': string
    readonly 'dashboard-neural-tools': string
    readonly 'dashboard-neural-title': string
    readonly 'dashboard-neural-buttons': string
    readonly 'dashboard-neural-btn': string
    readonly 'dashboard-status-footer': string
    readonly 'tab-content': string
    readonly 'agi-eco': string
    readonly 'agi-eco-root': string
    readonly 'agi-eco-title': string
    readonly 'agi-eco-desc': string
    readonly 'agi-eco-grid': string
    readonly 'agi-eco-card': string
    readonly 'agi-eco-card-header': string
    readonly 'agi-eco-icon': string
    readonly 'agi-eco-card-title': string
    readonly 'agi-eco-form': string
    readonly 'agi-eco-input': string
    readonly 'agi-eco-select': string
    readonly 'agi-eco-buttons': string
    readonly 'agi-eco-btn': string
    readonly 'agi-eco-status': string
}
export = styles
