import { NextRequest, NextResponse } from 'next/server';

// Force dynamic rendering - Web8 uses only real-time statistics
export const dynamic = 'force-dynamic';
export const revalidate = 0;

/**
 * Web8 Dynamic Sitemap Generator
 * @author Ledjan Ahmati
 * @version 8.0.0-WEB8
 * @contact dealsjona@gmail.com
 */

interface SitemapEntry {
  loc: string;
  lastmod: string;
  changefreq: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  priority: number;
}

interface Web8Route {
  path: string;
  changefreq: SitemapEntry['changefreq'];
  priority: number;
  isPublic: boolean;
  category: 'core' | 'agi' | 'neural' | 'demo' | 'api';
}

// Web8 Platform Routes Configuration
const web8Routes: Web8Route[] = [
  // Core Platform Routes
  { path: '/', changefreq: 'daily', priority: 1.0, isPublic: true, category: 'core' },
  { path: '/agi-dashboard', changefreq: 'hourly', priority: 1.0, isPublic: true, category: 'core' },
  
  // AGI Core Routes
  { path: '/agi', changefreq: 'daily', priority: 0.9, isPublic: true, category: 'agi' },
  { path: '/ultra-agi-chat', changefreq: 'daily', priority: 0.9, isPublic: true, category: 'agi' },
  
  // Neural Network Routes
  { path: '/neural-demo', changefreq: 'daily', priority: 0.8, isPublic: true, category: 'neural' },
  { path: '/fluid-demo', changefreq: 'weekly', priority: 0.7, isPublic: true, category: 'neural' },
  { path: '/guardian-demo', changefreq: 'weekly', priority: 0.7, isPublic: true, category: 'neural' },
  { path: '/openmind', changefreq: 'weekly', priority: 0.8, isPublic: true, category: 'neural' },
  
  // Demo Routes
  { path: '/agi-bio-demo', changefreq: 'weekly', priority: 0.6, isPublic: true, category: 'demo' },
  { path: '/agi-eco-demo', changefreq: 'weekly', priority: 0.6, isPublic: true, category: 'demo' },
  { path: '/agi-demo', changefreq: 'weekly', priority: 0.6, isPublic: true, category: 'demo' },
  { path: '/agixeco-demo', changefreq: 'weekly', priority: 0.6, isPublic: true, category: 'demo' },
  { path: '/cva-demo', changefreq: 'monthly', priority: 0.5, isPublic: true, category: 'demo' },
  { path: '/browser', changefreq: 'monthly', priority: 0.5, isPublic: true, category: 'demo' },
  
  // Public API Routes
  { path: '/api/rss', changefreq: 'daily', priority: 0.4, isPublic: true, category: 'api' },
];

function generateSitemapXML(entries: SitemapEntry[]): string {
  const timestamp = new Date().toISOString();
  
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml"
        xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
        xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
  
  <!-- Generated by Web8 Platform at ${timestamp} -->
  <!-- Creator: Ledjan Ahmati | Version: 8.0.0-WEB8 -->
  
${entries.map(entry => `  <url>
    <loc>${entry.loc}</loc>
    <lastmod>${entry.lastmod}</lastmod>
    <changefreq>${entry.changefreq}</changefreq>
    <priority>${entry.priority}</priority>
    <mobile:mobile/>
  </url>`).join('\n')}
  
</urlset>`;
}

function generateSitemapIndex(): string {
  const timestamp = new Date().toISOString();
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://ultrawebthinking.vercel.app';
  
  return `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <!-- Web8 AGI Platform Sitemap Index -->
  <!-- Generated: ${timestamp} -->
  <!-- Creator: Ledjan Ahmati | Version: 8.0.0-WEB8 -->
  
  <sitemap>
    <loc>${baseUrl}/sitemap-core.xml</loc>
    <lastmod>${timestamp}</lastmod>
  </sitemap>
  
  <sitemap>
    <loc>${baseUrl}/sitemap-agi.xml</loc>
    <lastmod>${timestamp}</lastmod>
  </sitemap>
  
  <sitemap>
    <loc>${baseUrl}/sitemap-neural.xml</loc>
    <lastmod>${timestamp}</lastmod>
  </sitemap>
  
  <sitemap>
    <loc>${baseUrl}/sitemap-demos.xml</loc>
    <lastmod>${timestamp}</lastmod>
  </sitemap>
  
  <sitemap>
    <loc>${baseUrl}/sitemap-api.xml</loc>
    <lastmod>${timestamp}</lastmod>
  </sitemap>
  
</sitemapindex>`;
}

export async function GET(request: NextRequest) {
  try {
    // Use searchParams directly from NextRequest
    const type = request.nextUrl.searchParams.get('type') || 'index';
    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://ultrawebthinking.vercel.app';
    const timestamp = new Date().toISOString();

    console.log(`🗺️ Web8 Sitemap: Generating ${type} sitemap`);

    switch (type) {
      case 'index':
        return new NextResponse(generateSitemapIndex(), {
          headers: {
            'Content-Type': 'application/xml',
            'Cache-Control': 'public, max-age=3600', // 1 hour cache
          },
        });

      case 'core':
        const coreRoutes = web8Routes
          .filter(route => route.category === 'core' && route.isPublic)
          .map(route => ({
            loc: `${baseUrl}${route.path}`,
            lastmod: timestamp,
            changefreq: route.changefreq,
            priority: route.priority,
          }));
        
        return new NextResponse(generateSitemapXML(coreRoutes), {
          headers: {
            'Content-Type': 'application/xml',
            'Cache-Control': 'public, max-age=1800', // 30 minutes cache
          },
        });

      case 'agi':
        const agiRoutes = web8Routes
          .filter(route => route.category === 'agi' && route.isPublic)
          .map(route => ({
            loc: `${baseUrl}${route.path}`,
            lastmod: timestamp,
            changefreq: route.changefreq,
            priority: route.priority,
          }));
        
        return new NextResponse(generateSitemapXML(agiRoutes), {
          headers: {
            'Content-Type': 'application/xml',
            'Cache-Control': 'public, max-age=1800',
          },
        });

      case 'neural':
        const neuralRoutes = web8Routes
          .filter(route => route.category === 'neural' && route.isPublic)
          .map(route => ({
            loc: `${baseUrl}${route.path}`,
            lastmod: timestamp,
            changefreq: route.changefreq,
            priority: route.priority,
          }));
        
        return new NextResponse(generateSitemapXML(neuralRoutes), {
          headers: {
            'Content-Type': 'application/xml',
            'Cache-Control': 'public, max-age=3600',
          },
        });

      case 'demos':
        const demoRoutes = web8Routes
          .filter(route => route.category === 'demo' && route.isPublic)
          .map(route => ({
            loc: `${baseUrl}${route.path}`,
            lastmod: timestamp,
            changefreq: route.changefreq,
            priority: route.priority,
          }));
        
        return new NextResponse(generateSitemapXML(demoRoutes), {
          headers: {
            'Content-Type': 'application/xml',
            'Cache-Control': 'public, max-age=7200', // 2 hours cache
          },
        });

      case 'api':
        const apiRoutes = web8Routes
          .filter(route => route.category === 'api' && route.isPublic)
          .map(route => ({
            loc: `${baseUrl}${route.path}`,
            lastmod: timestamp,
            changefreq: route.changefreq,
            priority: route.priority,
          }));
        
        return new NextResponse(generateSitemapXML(apiRoutes), {
          headers: {
            'Content-Type': 'application/xml',
            'Cache-Control': 'public, max-age=3600',
          },
        });

      default:
        return NextResponse.json(
          { error: 'Invalid sitemap type', available: ['index', 'core', 'agi', 'neural', 'demos', 'api'] },
          { status: 400 }
        );
    }

  } catch (error) {
    console.error('❌ Web8 Sitemap Error:', error);
    return NextResponse.json(
      { error: 'Failed to generate sitemap', message: error.message },
      { status: 500 }
    );
  }
}
