/**
 * @author Ledjan Ahmati
 * @version 8.0.0-WEB8
 * @contact dealsjona@gmail.com
 * Industrial AGI Test Center - Real API Testing Interface
 */

import React, { useState, useEffect } from 'react';
import Head from 'next/head';

interface ApiResponse {
  success: boolean;
  data?: any;
  error?: any;
  meta?: any;
}

interface TestResult {
  endpoint: string;
  method: string;
  status: number;
  response: any;
  duration: number;
  timestamp: string;
}

const IndustrialTestCenter = () => {
  const [activeTab, setActiveTab] = useState('search');
  const [results, setResults] = useState<TestResult[]>([]);
  const [loading, setLoading] = useState<Record<string, boolean>>({});

  // Search state
  const [searchQuery, setSearchQuery] = useState('artificial intelligence trends 2024');
  const [searchOptions, setSearchOptions] = useState({
    count: 10,
    enhanceKeywords: true,
    analyzeCredibility: true
  });

  // Analysis state
  const [analysisText, setAnalysisText] = useState('Artificial intelligence is transforming industries worldwide. Machine learning algorithms are becoming more sophisticated, enabling automation and intelligent decision-making across various sectors.');
  const [analysisUrl, setAnalysisUrl] = useState('');

  // Report state
  const [reportType, setReportType] = useState('quick');
  const [reportTitle, setReportTitle] = useState('Industrial AGI Test Report');
  const [reportContent, setReportContent] = useState('This is a test report generated by the Industrial AGI system.');

  // System stats
  const [systemStats, setSystemStats] = useState<any>(null);
  const [alertCount, setAlertCount] = useState(0);

  const callAPI = async (
    endpoint: string, 
    method: string = 'POST', 
    data?: any
  ): Promise<TestResult> => {
    const startTime = Date.now();
    
    try {
      const response = await fetch(endpoint, {
        method,
        headers: {
          'Content-Type': 'application/json',
        },
        ...(method !== 'GET' && data && { body: JSON.stringify(data) })
      });

      const responseData = await response.json();
      const duration = Date.now() - startTime;

      const result: TestResult = {
        endpoint,
        method,
        status: response.status,
        response: responseData,
        duration,
        timestamp: new Date().toISOString()
      };

      setResults(prev => [result, ...prev.slice(0, 19)]); // Keep last 20 results
      return result;

    } catch (error) {
      const duration = Date.now() - startTime;
      const result: TestResult = {
        endpoint,
        method,
        status: 0,
        response: { error: error instanceof Error ? error.message : 'Network error' },
        duration,
        timestamp: new Date().toISOString()
      };

      setResults(prev => [result, ...prev.slice(0, 19)]);
      return result;
    }
  };

  const testSearch = async () => {
    setLoading(prev => ({ ...prev, search: true }));
    
    await callAPI('/api/industrial/search', 'POST', {
      query: searchQuery,
      options: {
        count: searchOptions.count,
        enhancement: {
          extractKeywords: searchOptions.enhanceKeywords,
          scoreCredibility: searchOptions.analyzeCredibility
        },
        neural: {
          processIntent: true,
          generateSuggestions: true
        }
      }
    });

    setLoading(prev => ({ ...prev, search: false }));
  };

  const testAnalysis = async () => {
    setLoading(prev => ({ ...prev, analysis: true }));
    
    const data = analysisUrl 
      ? { url: analysisUrl }
      : { text: analysisText };

    await callAPI('/api/industrial/analyze', 'POST', data);

    setLoading(prev => ({ ...prev, analysis: false }));
  };

  const testReport = async () => {
    setLoading(prev => ({ ...prev, report: true }));
    
    await callAPI('/api/industrial/report', 'POST', {
      type: reportType,
      data: {
        title: reportTitle,
        content: reportContent
      },
      options: {
        format: 'base64'
      }
    });

    setLoading(prev => ({ ...prev, report: false }));
  };

  const testStats = async () => {
    setLoading(prev => ({ ...prev, stats: true }));
    
    const result = await callAPI('/api/industrial/stats?action=current', 'GET');
    
    if (result.response.success) {
      setSystemStats(result.response.data);
    }

    setLoading(prev => ({ ...prev, stats: false }));
  };

  const testAlerts = async () => {
    setLoading(prev => ({ ...prev, alerts: true }));
    
    const result = await callAPI('/api/industrial/stats?action=alerts', 'GET');
    
    if (result.response.success) {
      setAlertCount(result.response.data.active.length);
    }

    setLoading(prev => ({ ...prev, alerts: false }));
  };

  const testIngest = async () => {
    setLoading(prev => ({ ...prev, ingest: true }));
    
    // Submit a batch job
    await callAPI('/api/industrial/ingest?action=submit', 'POST', {
      type: 'batch',
      data: {
        operations: [
          { type: 'search', query: 'machine learning' },
          { type: 'analysis', text: 'AI is the future of technology.' }
        ]
      }
    });

    setLoading(prev => ({ ...prev, ingest: false }));
  };

  useEffect(() => {
    // Auto-refresh system stats every 30 seconds
    const interval = setInterval(() => {
      if (!loading.stats) {
        testStats();
      }
    }, 30000);

    // Initial load
    testStats();
    testAlerts();

    return () => clearInterval(interval);
  }, []);

  const formatResponse = (response: any) => {
    return JSON.stringify(response, null, 2);
  };

  const getStatusColor = (status: number) => {
    if (status === 0) return 'text-red-500';
    if (status >= 200 && status < 300) return 'text-green-500';
    if (status >= 400) return 'text-red-500';
    return 'text-yellow-500';
  };

  return (
    <>
      <Head>
        <title>Industrial AGI Test Center - UltraWeb v8.0.0</title>
        <meta name="description" content="Test the Industrial AGI APIs with real data processing" />
      </Head>

      <div className="min-h-screen bg-gray-900 text-white">
        {/* Header */}
        <div className="bg-gray-800 border-b border-gray-700">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex items-center justify-between h-16">
              <div className="flex items-center">
                <h1 className="text-xl font-bold text-blue-400">🏭 Industrial AGI Test Center</h1>
                <span className="ml-3 px-2 py-1 bg-blue-600 text-xs rounded">v8.0.0-WEB8</span>
              </div>
              
              <div className="flex items-center space-x-4">
                {systemStats && (
                  <div className="text-sm">
                    <span className="text-gray-400">Performance:</span>
                    <span className={`ml-1 font-bold ${systemStats.performance.score > 80 ? 'text-green-400' : 
                                                     systemStats.performance.score > 60 ? 'text-yellow-400' : 'text-red-400'}`}>
                      {systemStats.performance.score}%
                    </span>
                  </div>
                )}
                
                {alertCount > 0 && (
                  <div className="px-2 py-1 bg-red-600 text-xs rounded">
                    {alertCount} Alert{alertCount > 1 ? 's' : ''}
                  </div>
                )}
                
                <div className="text-xs text-gray-400">
                  Last updated: {new Date().toLocaleTimeString()}
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Left Panel - Tests */}
            <div className="lg:col-span-2">
              {/* Tab Navigation */}
              <div className="flex space-x-1 bg-gray-800 p-1 rounded-lg mb-6">
                {[
                  { id: 'search', label: '🔍 Search', icon: '🔍' },
                  { id: 'analysis', label: '📊 Analysis', icon: '📊' },
                  { id: 'reports', label: '📄 Reports', icon: '📄' },
                  { id: 'system', label: '🔧 System', icon: '🔧' },
                  { id: 'ingest', label: '📥 Ingest', icon: '📥' }
                ].map(tab => (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    className={`flex-1 px-3 py-2 text-sm font-medium rounded-md transition-colors ${
                      activeTab === tab.id
                        ? 'bg-blue-600 text-white'
                        : 'text-gray-300 hover:text-white hover:bg-gray-700'
                    }`}
                  >
                    {tab.label}
                  </button>
                ))}
              </div>

              {/* Search Tab */}
              {activeTab === 'search' && (
                <div className="bg-gray-800 rounded-lg p-6">
                  <h2 className="text-lg font-bold mb-4">🔍 Industrial Web Search</h2>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium mb-2">Search Query</label>
                      <input
                        type="text"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md text-white"
                        placeholder="Enter search query..."
                      />
                    </div>
                    
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="block text-sm font-medium mb-2">Result Count</label>
                        <select
                          value={searchOptions.count}
                          onChange={(e) => setSearchOptions(prev => ({ ...prev, count: parseInt(e.target.value) }))}
                          className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md text-white"
                        >
                          <option value={5}>5 results</option>
                          <option value={10}>10 results</option>
                          <option value={20}>20 results</option>
                          <option value={50}>50 results</option>
                        </select>
                      </div>
                      
                      <div className="space-y-2">
                        <label className="flex items-center">
                          <input
                            type="checkbox"
                            checked={searchOptions.enhanceKeywords}
                            onChange={(e) => setSearchOptions(prev => ({ ...prev, enhanceKeywords: e.target.checked }))}
                            className="mr-2"
                          />
                          Enhance Keywords
                        </label>
                        <label className="flex items-center">
                          <input
                            type="checkbox"
                            checked={searchOptions.analyzeCredibility}
                            onChange={(e) => setSearchOptions(prev => ({ ...prev, analyzeCredibility: e.target.checked }))}
                            className="mr-2"
                          />
                          Analyze Credibility
                        </label>
                      </div>
                    </div>
                    
                    <button
                      onClick={testSearch}
                      disabled={loading.search}
                      className="w-full px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {loading.search ? '🔄 Searching...' : '🔍 Test Search API'}
                    </button>
                  </div>
                </div>
              )}

              {/* Analysis Tab */}
              {activeTab === 'analysis' && (
                <div className="bg-gray-800 rounded-lg p-6">
                  <h2 className="text-lg font-bold mb-4">📊 Text Analysis</h2>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium mb-2">Analysis Type</label>
                      <div className="flex space-x-4">
                        <label className="flex items-center">
                          <input
                            type="radio"
                            name="analysisType"
                            value="text"
                            checked={!analysisUrl}
                            onChange={() => setAnalysisUrl('')}
                            className="mr-2"
                          />
                          Text Analysis
                        </label>
                        <label className="flex items-center">
                          <input
                            type="radio"
                            name="analysisType"
                            value="url"
                            checked={!!analysisUrl}
                            onChange={() => setAnalysisUrl('https://example.com')}
                            className="mr-2"
                          />
                          URL Analysis
                        </label>
                      </div>
                    </div>
                    
                    {!analysisUrl ? (
                      <div>
                        <label className="block text-sm font-medium mb-2">Text Content</label>
                        <textarea
                          value={analysisText}
                          onChange={(e) => setAnalysisText(e.target.value)}
                          rows={6}
                          className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md text-white"
                          placeholder="Enter text to analyze..."
                        />
                      </div>
                    ) : (
                      <div>
                        <label className="block text-sm font-medium mb-2">URL to Analyze</label>
                        <input
                          type="url"
                          value={analysisUrl}
                          onChange={(e) => setAnalysisUrl(e.target.value)}
                          className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md text-white"
                          placeholder="https://example.com/article"
                        />
                      </div>
                    )}
                    
                    <button
                      onClick={testAnalysis}
                      disabled={loading.analysis}
                      className="w-full px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {loading.analysis ? '🔄 Analyzing...' : '📊 Test Analysis API'}
                    </button>
                  </div>
                </div>
              )}

              {/* Reports Tab */}
              {activeTab === 'reports' && (
                <div className="bg-gray-800 rounded-lg p-6">
                  <h2 className="text-lg font-bold mb-4">📄 PDF Report Generation</h2>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium mb-2">Report Type</label>
                      <select
                        value={reportType}
                        onChange={(e) => setReportType(e.target.value)}
                        className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md text-white"
                      >
                        <option value="quick">Quick Report</option>
                        <option value="search">Search Report</option>
                        <option value="analysis">Analysis Report</option>
                        <option value="custom">Custom Report</option>
                      </select>
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium mb-2">Report Title</label>
                      <input
                        type="text"
                        value={reportTitle}
                        onChange={(e) => setReportTitle(e.target.value)}
                        className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md text-white"
                        placeholder="Enter report title..."
                      />
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium mb-2">Report Content</label>
                      <textarea
                        value={reportContent}
                        onChange={(e) => setReportContent(e.target.value)}
                        rows={4}
                        className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md text-white"
                        placeholder="Enter report content..."
                      />
                    </div>
                    
                    <button
                      onClick={testReport}
                      disabled={loading.report}
                      className="w-full px-4 py-2 bg-purple-600 text-white rounded-md hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {loading.report ? '🔄 Generating...' : '📄 Test Report API'}
                    </button>
                  </div>
                </div>
              )}

              {/* System Tab */}
              {activeTab === 'system' && (
                <div className="bg-gray-800 rounded-lg p-6">
                  <h2 className="text-lg font-bold mb-4">🔧 System Monitoring</h2>
                  
                  <div className="grid grid-cols-2 gap-4 mb-6">
                    <button
                      onClick={testStats}
                      disabled={loading.stats}
                      className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50"
                    >
                      {loading.stats ? '🔄 Loading...' : '📊 Get System Stats'}
                    </button>
                    
                    <button
                      onClick={testAlerts}
                      disabled={loading.alerts}
                      className="px-4 py-2 bg-yellow-600 text-white rounded-md hover:bg-yellow-700 disabled:opacity-50"
                    >
                      {loading.alerts ? '🔄 Loading...' : '⚠️ Check Alerts'}
                    </button>
                  </div>
                  
                  {systemStats && (
                    <div className="space-y-4">
                      <div className="grid grid-cols-3 gap-4">
                        <div className="bg-gray-700 p-3 rounded">
                          <div className="text-sm text-gray-400">CPU Usage</div>
                          <div className="text-lg font-bold text-blue-400">{systemStats.cpu.usage}%</div>
                        </div>
                        
                        <div className="bg-gray-700 p-3 rounded">
                          <div className="text-sm text-gray-400">Memory Usage</div>
                          <div className="text-lg font-bold text-green-400">{systemStats.memory.usagePercent}%</div>
                        </div>
                        
                        <div className="bg-gray-700 p-3 rounded">
                          <div className="text-sm text-gray-400">Performance</div>
                          <div className="text-lg font-bold text-purple-400">{systemStats.performance.score}%</div>
                        </div>
                      </div>
                      
                      <div className="bg-gray-700 p-3 rounded">
                        <div className="text-sm text-gray-400 mb-2">System Info</div>
                        <div className="text-sm">
                          <div>Platform: {systemStats.system.platform}</div>
                          <div>Architecture: {systemStats.system.arch}</div>
                          <div>Hostname: {systemStats.system.hostname}</div>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* Ingest Tab */}
              {activeTab === 'ingest' && (
                <div className="bg-gray-800 rounded-lg p-6">
                  <h2 className="text-lg font-bold mb-4">📥 Data Ingestion Pipeline</h2>
                  
                  <div className="space-y-4">
                    <p className="text-gray-400 text-sm">
                      Test the asynchronous data processing pipeline with batch operations.
                    </p>
                    
                    <button
                      onClick={testIngest}
                      disabled={loading.ingest}
                      className="w-full px-4 py-2 bg-orange-600 text-white rounded-md hover:bg-orange-700 disabled:opacity-50"
                    >
                      {loading.ingest ? '🔄 Submitting...' : '📥 Test Batch Ingest API'}
                    </button>
                    
                    <div className="text-sm text-gray-400">
                      This will submit a batch job containing search and analysis operations.
                      Check the Results panel for the job status and processing details.
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* Right Panel - Results */}
            <div>
              <div className="bg-gray-800 rounded-lg p-6">
                <h3 className="text-lg font-bold mb-4">📋 API Test Results</h3>
                
                <div className="space-y-3 max-h-96 overflow-y-auto">
                  {results.length === 0 ? (
                    <div className="text-gray-400 text-center py-8">
                      No tests run yet. Use the panels on the left to test APIs.
                    </div>
                  ) : (
                    results.map((result, index) => (
                      <div key={index} className="bg-gray-700 rounded p-3 text-xs">
                        <div className="flex items-center justify-between mb-2">
                          <span className="font-mono text-blue-400">
                            {result.method} {result.endpoint.split('?')[0]}
                          </span>
                          <span className={`font-bold ${getStatusColor(result.status)}`}>
                            {result.status}
                          </span>
                        </div>
                        
                        <div className="flex items-center justify-between text-gray-400 mb-2">
                          <span>{result.duration}ms</span>
                          <span>{new Date(result.timestamp).toLocaleTimeString()}</span>
                        </div>
                        
                        <details className="cursor-pointer">
                          <summary className="text-gray-300 hover:text-white">
                            {result.response.success ? '✅ Response' : '❌ Error'}
                          </summary>
                          <pre className="mt-2 p-2 bg-gray-900 rounded text-xs overflow-x-auto">
                            {formatResponse(result.response).substring(0, 500)}
                            {formatResponse(result.response).length > 500 && '...'}
                          </pre>
                        </details>
                      </div>
                    ))
                  )}
                </div>
                
                {results.length > 0 && (
                  <button
                    onClick={() => setResults([])}
                    className="w-full mt-4 px-3 py-1 bg-gray-600 text-white text-sm rounded hover:bg-gray-500"
                  >
                    Clear Results
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default IndustrialTestCenter;
